
import os
from sys import stderr
from flask import Flask, request, make_response, redirect, url_for, jsonify
from flask import render_template, session

app = Flask(__name__, template_folder='templates')

# Generated by os.urandom(16)
app.secret_key = b'\xcdt\x8dn\xe1\xbdW\x9d[}yJ\xfc\xa3~/'

responses = []

@app.route('/', methods=['GET'])
def home():
    html = render_template('home.html')
    response = make_response(html)
    return response

@app.route('/stages', methods=['GET'])
def stages():
    html = render_template('stages.html')
    response = make_response(html)
    return response

@app.route('/gettrait', methods=['POST'])
def gettrait():
    ans1 = request.form["1radio"]
    ans2 = request.form["2radio"]
    ans3 = request.form["3radio"]
    ans4 = request.form["4radio"]
    ans5 = request.form["5radio"]
    ans6 = request.form["6radio"]
    ans7 = request.form["7radio"]
    ans8 = request.form["8radio"]

    if ans1 == '4' and (ans2 == '2' or ans2 == '3'):
        trait1 = 'hopeful'
    else:
        trait1 = 'fearful, anxious, and insecure'

    if (ans3 == '3' or ans3 == '4') and (ans4 == '1' or ans4 == '2'):
        trait2 = 'willful and confident'
    else:
        trait2 = 'has low self-esteem, is shameful and doubtful'

    if (ans5 == '3' or ans5 == '4') and ans6 == '4':
        trait3 = 'has initative'
    else:
        trait3 = 'tends to feel guilt'

    if ans7 == '2' and ans8 == '3':
        trait4 = 'feels competent'
    else:
        trait4 = 'feels inferior'
    
    html = render_template('charactertraits.html', trait1=trait1, trait2=trait2, trait3=trait3, trait4=trait4)
    response = make_response(html)
    return response